image: registry.gitlab.com/pipeline-components/black:latest

stages:
  - lint

lint:
  stage: lint
  script:
    - pip install --upgrade pip
    - pip install flake8 pep8-naming flake8-import-order flake8-quotes
    - flake8 . 
    - black --check .
  only:
    - master
    - merge_requests 
  allow_failure: false  