image: registry.gitlab.com/pipeline-components/black:latest

stages:
  - lint

lint:
  stage: lint
  script:
    - pip install --upgrade pip
    - pip install flake8 pep8-naming flake8-import-order flake8-quotes black
    - flake8 --config=.flake8 .
    - black --check .
  only:
    - main
    - merge_requests
  allow_failure: false
