image: python:latest

stages:
  - lint
  - test
  - deploy

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install black flake8

black-formatting:
  stage: lint
  script:
    - black . --line-length 79  

lint-test-job:
  stage: test
  script:
    - flake8 . --count --show-source --statistics
  only:
    - merge_requests
    - main