image: python:latest

stages:
  - lint

lint:
  stage: lint
  script:
    - pip install --upgrade pip
    - pip install flake8 pep8-naming flake8-import-order flake8-quotes black
    - flake8 . 
    - black --check --skip-string-normalization .
  only:
    - master
    - merge_requests 
  allow_failure: false  