image: python:latest

stages:
  - lint

lint:
  stage: lint
  script:
    - pip install --upgrade pip
    - pip install flake8
    - flake8 . 
  only:
    - master
    - merge_requests 
  allow_failure: false  