# Generated by Django 4.2.16 on 2024-11-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст обращения",
                        verbose_name="текстовое поле",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания обращения",
                        null=True,
                        verbose_name="дата и время создания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GT", "получено"),
                            ("PR", "в обработке"),
                            ("OK", "ответ дан"),
                        ],
                        default="GT",
                        max_length=2,
                        verbose_name="статус обработки",
                    ),
                ),
            ],
            options={
                "verbose_name": "фидбек",
                "verbose_name_plural": "фидбек",
            },
        ),
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Имя автора обращения",
                        null=True,
                        verbose_name="имя отправителя",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Электронный адрес отправителя",
                        max_length=254,
                        verbose_name="почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "персональная информация",
                "verbose_name_plural": "персональные данные",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        db_column="from",
                        max_length=2,
                        verbose_name="начальное состояние",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        max_length=2, verbose_name="новое состояние"
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="фидбек пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                        verbose_name="фидбек",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="имя пользователя, отправившего фидбек",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог статусов",
                "verbose_name_plural": "логи статусов",
            },
        ),
        migrations.CreateModel(
            name="MultipleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to=feedback.models.MultipleFile.get_upload_path,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="файл прикрепленный к фидбеку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                        verbose_name="файл",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл",
                "verbose_name_plural": "файлы",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="personal_data",
            field=models.OneToOneField(
                blank=True,
                help_text="Ссылка на персональные данные автора",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="feedback.personaldata",
                verbose_name="персональная информация",
            ),
        ),
    ]
