# Generated by Django 4.2.16 on 2024-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="mail",
            field=models.EmailField(
                help_text="Электронный адрес отправителя",
                max_length=254,
                verbose_name="почта",
            ),
        ),
    ]
