# Generated by Django 4.2.16 on 2024-11-04 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0005_alter_statuslog_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Имя автора обращения",
                        null=True,
                        verbose_name="имя отправителя",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Электронный адрес отправителя",
                        max_length=254,
                        verbose_name="почта",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                help_text="фидбек",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="feedback.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                max_length=2, verbose_name="начальное состояние"
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                help_text="пользователь",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="personal_data",
            field=models.ForeignKey(
                blank=True,
                help_text="Ссылка на персональные данные автора",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="feedback.personaldata",
            ),
        ),
    ]
