# Generated by Django 4.2.16 on 2024-11-04 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0006_personaldata_remove_feedback_mail_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "фидбек",
                "verbose_name_plural": "фидбек",
            },
        ),
        migrations.AlterModelOptions(
            name="personaldata",
            options={
                "verbose_name": "персональная информация",
                "verbose_name_plural": "персональные данные",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="personal_data",
            field=models.ForeignKey(
                blank=True,
                help_text="Ссылка на персональные данные автора",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="feedback.personaldata",
                verbose_name="персональная информация",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                help_text="фидбек пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="feedback.feedback",
                verbose_name="фидбек",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                help_text="имя пользователя, отправившего фидбек",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
