# Generated by Django 4.2.16 on 2024-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0007_alter_feedback_options_alter_personaldata_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="files",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
