# Generated by Django 4.2.16 on 2024-11-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_alter_feedback_personal_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="personal_data",
            field=models.OneToOneField(
                blank=True,
                help_text="Ссылка на персональные данные автора",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="feedback.personaldata",
                verbose_name="персональная информация",
            ),
        ),
    ]
