# Generated by Django 4.2.16 on 2024-11-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_alter_feedback_personal_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="files",
            field=models.FileField(null=True, upload_to="uploads/db_uploads/"),
        ),
    ]
