# Generated by Django 4.2.16 on 2024-11-05 11:07

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0011_alter_feedback_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="files",
        ),
        migrations.CreateModel(
            name="MultipleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to=feedback.models.MultipleFile.get_upload_path,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="файл прикрепленный к фидбеку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                        verbose_name="файл",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл",
                "verbose_name_plural": "файлы",
            },
        ),
    ]
