# Generated by Django 4.2.16 on 2024-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0012_remove_feedback_files_multiplefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                db_column="from",
                max_length=2,
                verbose_name="начальное состояние",
            ),
        ),
    ]
