# Generated by Django 4.2.16 on 2024-11-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_proxyuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proxyuser",
            options={},
        ),
    ]
