# Generated by Django 4.2.16 on 2024-11-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_proxyuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
