# Generated by Django 4.2.16 on 2024-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_attempts_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
