# Generated by Django 4.2.16 on 2024-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_alter_rating_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
