# Generated by Django 4.2.16 on 2024-10-13 18:12

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0001_initial"),
        ("catalog", "0002_category_tag_item_is_published_item_text_and_more"),
        ("catalog", "0003_alter_item_text"),
        ("catalog", "0004_item_category_item_tags"),
        ("catalog", "0005_alter_category_options_alter_item_options_and_more"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Напишите название товара",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        help_text="Напишите слаг",
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Напишите вес товара",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Напишите название товара",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        help_text="Напишите слаг",
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Напишите название товара",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Напишите описание товара",
                        validators=[catalog.models.custom_validator],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="catalog.tag", verbose_name="Теги"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
