# Generated by Django 4.2.16 on 2024-10-13 10:27

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.TextField(max_length=150, verbose_name="Название"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        help_text="Напишите слаг",
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Напишите вес товара",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.TextField(max_length=150, verbose_name="Название"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        help_text="Напишите слаг",
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Напишите текст",
                null=True,
                validators=[catalog.models.custom_validator],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(max_length=150, verbose_name="Название"),
        ),
    ]
