# Generated by Django 4.2.16 on 2024-10-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0001_initial_squashed_0002_category_normalized_name_tag_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="images",
            field=models.ImageField(
                blank=True, upload_to="catalog/", verbose_name="изображения"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                blank=True,
                upload_to="catalog/",
                verbose_name="главное изображение",
            ),
        ),
    ]
