# Generated by Django 4.2.16 on 2024-10-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0004_remove_item_images_imagemodel"),
        ("catalog", "0005_mainimage_delete_imagemodel"),
        (
            "catalog",
            "0006_rename_id_category_item_id_rename_id_item_item_id_and_more",
        ),
    ]

    dependencies = [
        ("catalog", "0003_item_images_item_main_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="images",
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        upload_to="catalog/",
                        verbose_name="изображения",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="изображения",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.RenameField(
            model_name="category",
            old_name="id",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="id",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="id",
            new_name="item_id",
        ),
    ]
