# Generated by Django 4.2.16 on 2024-10-13 11:38

import catalog.models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_item_category_item_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                help_text="Напишите название товара",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                help_text="Напишите название товара",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                to="catalog.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Напишите описание товара",
                validators=[catalog.models.custom_validator],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="Напишите название товара",
                max_length=150,
                verbose_name="Название",
            ),
        ),
    ]
