# Generated by Django 4.2.16 on 2024-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="Напишите название тега (макс. кол-во символов 150, название должно быть уникальным)",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Напишите слаг (макс. кол-во символов 200)",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
