# Generated by Django 4.2.16 on 2024-10-16 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0006_alter_category_name_alter_item_name_alter_tag_name"),
        ("catalog", "0007_alter_category_slug"),
    ]

    dependencies = [
        (
            "catalog",
            "0001_initial_squashed_0005_alter_category_options_alter_item_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                help_text="Напишите название товара",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                help_text="Напишите название товара",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="Напишите название товара",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.TextField(
                help_text="Напишите слаг",
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="слаг",
            ),
        ),
    ]
