# Generated by Django 4.2.16 on 2024-10-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_mainimage_delete_imagemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="id",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="id",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="id",
            new_name="item_id",
        ),
    ]
