# Generated by Django 4.2.16 on 2024-10-23 17:16

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0004_remove_item_images_imagemodel_squashed_0006_rename_id_category_item_id_rename_id_item_item_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Напишите описание товара",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
    ]
