# Generated by Django 4.2.16 on 2024-10-16 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_category_name_alter_item_name_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.TextField(
                help_text="Напишите слаг",
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="слаг",
            ),
        ),
    ]
