# Generated by Django 4.2.16 on 2024-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                help_text="Напишите название категории (макс. кол-во символов 150, название должно быть уникальным)",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
    ]
