# Generated by Django 4.2.16 on 2024-10-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_item_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainimage",
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
        migrations.RemoveField(
            model_name="mainimage",
            name="images",
        ),
        migrations.AddField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="catalog/",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="catalog/",
                        verbose_name="доп. изображение",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        related_query_name="image",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "доп. изображение",
                "verbose_name_plural": "доп. изображения",
            },
        ),
    ]
