# Generated by Django 4.2.16 on 2024-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0008_alter_mainimage_options_remove_item_main_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="показывать на главной"
            ),
        ),
    ]
