# Generated by Django 4.2.16 on 2024-10-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_item_is_on_main"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="item_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="item_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="item_id",
            new_name="id",
        ),
    ]
