# Generated by Django 4.2.16 on 2024-10-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0010_rename_item_id_category_id_rename_item_id_item_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="id",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="id",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="id",
            new_name="item_id",
        ),
    ]
