# Generated by Django 4.2.16 on 2024-10-30 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_item_created_at_item_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="item_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="item_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="item_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Напишите Слаг",
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="слаг",
            ),
        ),
    ]
